### ISSUE TITLE
pyglui for Python 3.7

### ISSUE THREAD

**Issue by crissallan** [pupil-labs/pyglui#110]
Hi, I'd like to know is there a release for Python 3.7, I try to install the pyglui-1.25-cp36-cp36m-win_amd64.whl. But got the

 ERROR: pyglui-1.25-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

then I tried to rename this wheel file as pyglui-1.25-cp37-cp37m-win_amd64.whl. The installation was successful but when I ran the "run_capture.bat" file, another error raised：
from pyglui import ui, cygl, __version__ as pyglui_version
ImportError: cannot import name 'ui' from 'pyglui' 

Is there any solution for this?

**Comment by pfaion** [comment]
Hi @crissallan 
we don't provide binary wheels for Windows/Python37 currently.
You can try to compile pyglui from source on you system though, which should work. Note that there is currently no documentation available on how to do this, but a starting point would be to try
```
pip install git+https://github.com/pupil-labs/pyglui
```
Make sure pip is the pip of your Python37.

If this does not work out of the box, you can try setting up the Windows development environment that we use for [Pupil](https://github.com/pupil-labs/pupil). Here's the relevant guide:
https://github.com/pupil-labs/pupil/blob/master/docs/dependencies-windows.md

This probably has more stuff than you need for pyglui. But you will have to figure this out for yourself I'm afraid.

I'll close this issue for now as your main question seems to be answered. If you run into trouble compiling from source, feel free to open a new issue.

**Comment by papr** [comment]
Please be also aware that Pupil won't run on Python 3.7 since one of its dependencies (pyaudio) is currently not available for Python 3.7
