### ISSUE TITLE
Missing Designs for Sliders

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pyglui#15]
If you adjust the 'Interface size' then the sliders design has sometimes no line or dots in the background.
This could be confusing, because in this way it looks like a on-off-button.

Usually this happens if the interface size is getting smaller, suddenly the graphics vanishing.

**Comment by mkassner** [comment]
This is a bug I have only observed on Linux machines (and only older ones.) 

@fneitzel Can you send a screenshot?
