### ISSUE TITLE
Allow other versions of glew on Darwin

### ISSUE THREAD

**Issue by toshikurauchi** [pupil-labs/pyglui#19]
When installing glew with homebrew I got the version 1.10.0. However in setup.py the glew version is hardcoded as 1.11.0 (`glew_header = '/usr/local/Cellar/glew/1.11.0/include/GL/glew.h'`) so I had to manually change it to 1.10.0.

It would be nice if it could automatically locate the correct version.

**Comment by mkassner** [comment]
If made setup.py be a bit smarter about the path. Please reopen if this does not work for you.
