### ISSUE TITLE
Cythonizing pyglui fails on Win7 32bit

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pyglui#20]
Hi guys!

Not quite sure what's the issue here in the moment.

missing cimport in module 'cygl': pyglui/ui.pyx
missing cimport in module 'cygl': pyglui/graph.pyx

Or did my cygl build already fail?

C:\Users\testing\git\pyglui>python setup.py install
'glew.pxd' is up-to-date.
missing cimport in module 'cygl': pyglui/ui.pyx
missing cimport in module 'cygl': pyglui/graph.pyx
Compiling pyglui/ui.pyx because it changed.
Compiling pyglui/graph.pyx because it changed.
Cythonizing pyglui/graph.pyx

Error compiling Cython file:
:------------------------------------------------------------
...
from cython cimport view
from cygl cimport glew as gl
^
:------------------------------------------------------------

pyglui\graph.pyx:2:0: 'glew.pxd' not found

Error compiling Cython file:
:------------------------------------------------------------
...
from cython cimport view
from cygl cimport glew as gl
                 ^
:------------------------------------------------------------

pyglui\graph.pyx:2:18: Name 'glew' not declared in module 'cygl'

Error compiling Cython file:
:------------------------------------------------------------
...
from cython cimport view
from cygl cimport glew as gl
from cygl cimport utils
^
:------------------------------------------------------------

pyglui\graph.pyx:3:0: 'utils.pxd' not found

Error compiling Cython file:
:------------------------------------------------------------
...
from cython cimport view
from cygl cimport glew as gl
from cygl cimport utils
                 ^
:------------------------------------------------------------

pyglui\graph.pyx:3:18: Name 'utils' not declared in module 'cygl'

Error compiling Cython file:
:------------------------------------------------------------
...
def push_view(int w=0,int h=0):
    '''
    Sets up pixel based gl coord system.
    Use this to prepare rendering of graphs.
    '''
    gl.glMatrixMode(gl.GL_PROJECTION)
     ^
:------------------------------------------------------------

pyglui\graph.pyx:20:6: undeclared name not builtin: gl
Traceback (most recent call last):
  File "setup.py", line 115, in <module>
    ext_modules=cythonize(extensions)
  File "C:\Python34\lib\site-packages\Cython\Build\Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "C:\Python34\lib\site-packages\Cython\Build\Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pyglui/graph.pyx

**Comment by mkassner** [comment]
seems like glew.pxd was not generated.
