### ISSUE TITLE
setup.py install failed on Ubuntu 15.04 64 bit

### ISSUE THREAD

**Issue by stuaxo** [pupil-labs/pyglui#24]
I installed cygl, then tried install pyglui but it failed ..

```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from pyglui.cygl.glew_pxd import generate_pxd
ImportError: No module named cygl.glew_pxd
```

**Comment by cpicanco** [comment]
Note that you must clone pyglui with the --recursive flag first, please take a look close look at the wiki.

Also, note that Ubuntu 15.04 64 bit is not offitially supported, but Ubuntu 14.04 LTS 64 bits. Regardless of that, I encorage you to give it a try. :smile:

**Comment by stuaxo** [comment]
Cheers, that works :)

* setup.py should probably include the  psutil  requirement and version. 

* the newer version of psutil seems to have ps.cpu_percent  instead of  ps.get_cpu_percent

**Comment by mkassner** [comment]
Since psutil is only needed for the demo I left it out if the requirement. But I will add a note in the README.
