### ISSUE TITLE
Wheel release for v0.7 missing

### ISSUE THREAD

**Issue by papr** [pupil-labs/pyglui#28]
Hey there! Thanks for your great work. Could you create a Wheel release for the current version v0.7? It would help some colleagues a lot. :)

**Comment by mkassner** [comment]
@MichaelBarz  can you do that?

**Comment by MichaelBarz** [comment]
Yes, I can do that.

**Comment by MichaelBarz** [comment]
Hi, done ;) Actually it is v0.8...

**Comment by papr** [comment]
Thank you so much.
