### ISSUE TITLE
Menu title is neither wrapped nor clipped if it is longer than menu width 

### ISSUE THREAD

**Issue by papr** [pupil-labs/pyglui#34]
![image](https://cloud.githubusercontent.com/assets/168390/18130362/08a489e2-6f8f-11e6-8b4f-ddb4078e4804.png)

**Comment by mkassner** [comment]
Yes. I think they should be clipped.

**Comment by papr** [comment]
**Solution:** Use `draw_limited_text()` instead of `draw_text()`
![image](https://cloud.githubusercontent.com/assets/168390/18174286/4f29b098-706d-11e6-8882-36c5835f1399.png)
