### ISSUE TITLE
Reduce area of the square to minimize FitBox onclick

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pyglui#35]
Hi, I have a suggestion.

### The problem

Because the entire title bar area is being used, the minimize onClick  is conflicting with the BringToFront onClick functionality.

### Solution 1

Instead of using the entire title bar area, the minimize area onClick could be reduced to the ICON square (![square](https://cloud.githubusercontent.com/assets/6511849/18134600/4e6ea31e-6f75-11e6-855f-05793f746771.png)).

### Solution 2

Minimize onDoubleClick in the entire title bar. (However, this conflicts with existing standards, double click on the title bar usually means "expand the window to client boundaries" or "reduce the window to the last reduced state".)

**Comment by papr** [comment]
### Solution 3
Successful executed `BringToFront` action consumes the input. Therefore it would only minimize if the menu is already in front.

@cpicanco What do you think?

**Comment by cpicanco** [comment]
Good!

**Comment by mkassner** [comment]
Consumption of input would be strange if the window is already fully
visible.

I would try solution 1 and see how that feels.

M

**Comment by cpicanco** [comment]
@Moritz, @papr 's suggestion implies that the consumption of the input must not occur if the window is fully visible.

**Comment by mkassner** [comment]
Yes, while thats possible. Its technically cumbersome and I dont think that
it would feel consistent/logical for the user.

**Comment by cpicanco** [comment]
Well, suggestion 1 then!

**Comment by papr** [comment]
@cpicanco Could you test the PR?

**Comment by cpicanco** [comment]
@papr , yep

**Comment by cpicanco** [comment]
Functionality is working. However, I think I have found a bug. I checked and it was not introduced by any commit since fd3faf098b8ae0d3a991415600d714e52668fc48.

I will create a separated issue for that.

**Comment by cpicanco** [comment]
#37
