### ISSUE TITLE
Allow on mouse wheel in drop down list.

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pyglui#42]
### Problem

Drop down element is static. If it is full of stuff (like in the pupil player/capture plugin list) the user will not be able to select anything beyond the visible items (of course).
### Solution 1 (fake)

First I thought  a tab ui element would be great. However, it is too complicated and does not solve the visibility problem for the tabs themselves:
![screenshot from 2016-10-26 13 40 08](https://cloud.githubusercontent.com/assets/6511849/19735387/be8f3d6a-9b81-11e6-84a3-c648df8fa0fe.png)
### Solution 1 (For sure)

Allowing sliding (on mouse wheel) of the items in the drop down is enough and solves the visibility problem definitely.  Prepending fixed names to the items with a code and sorting the list allow organizing things prettier.

**Comment by mkassner** [comment]
Hi! 

I think scrolling the dropdown would be nice. A bit of work to implement though.

Maybe a simple fix is to use a scrolling menu for the player main menu?

**Comment by cpicanco** [comment]
Yes, it would be a simpler fix!

**Comment by mkassner** [comment]
ok fixed in player.
