### ISSUE TITLE
Font loading fails if font directory has unicode characters

### ISSUE THREAD

**Issue by papr** [pupil-labs/pyglui#44]

**Comment by papr** [comment]
Well, bad news, @willpatera. This is an Windows problem only. It seems that `fopen` on Windows cannot handle utf-8 encoded `char*`... [fopen call in fontstash](https://github.com/memononen/fontstash/blob/7e837c205fde6ac416685131653e1f3c722bb027/src/fontstash.h#L858)

On Ubuntu, Pupil Capture loads font with unicode directories without problems.

**Comment by willpatera** [comment]
@papr did you review docs here 👉  https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx#Anchor_3

**Comment by mkassner** [comment]
So this is actually a https://github.com/memononen/fontstash issue . So I just made one: https://github.com/memononen/fontstash/issues/28

A note on attempting to fix this:  We dont need to load a unicode file. We actually need to load a file with a unicode name/path ->
world of pain: http://stackoverflow.com/questions/21402742/fopen-with-unicode-filename

This looks like something we should contract IMHO.

**Comment by mkassner** [comment]
OK. I guess the task is to make a PR to fontstash and add this: https://github.com/Wohlstand/UTF8-fopen/blob/master/check.c

**Comment by mkassner** [comment]
this is fixed with https://github.com/memononen/fontstash/pull/37

this commit set the correct submodule version:  f2c4529
