### ISSUE TITLE
Pyglui installation

### ISSUE THREAD

**Issue by Mistretech** [pupil-labs/pyglui#50]
You get some compatibility problem with the nvidia driver 375.66. Each ldconfig return an error from the others linux dependencies and the only library which won't install because of it is pyglui, i had to apply this command to correct it : 
sudo mv /usr/lib/nvidia-375/libEGL.so.1 /usr/lib/nvidia-375/libEGL.so.1.org
sudo mv /usr/lib32/nvidia-375/libEGL.so.1 /usr/lib32/nvidia-375/libEGL.so.1.org
sudo ln -s /usr/lib/nvidia-375/libEGL.so.375.39 /usr/lib/nvidia-375/libEGL.so.1
sudo ln -s /usr/lib32/nvidia-375/libEGL.so.375.39 /usr/lib32/nvidia-375/libEGL.so.

Come from  : https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-375/+bug/1662860 

The new version of nvidia driver solve it but you have to install the x86 compatibility with. 

I don't know if it will help or maybe I am in the wrong section not but i spend the whole day to find the problem and correct it. 

Best regard,

**Comment by papr** [comment]
Stale
