### ISSUE TITLE
Any prebuilt windows whl

### ISSUE THREAD

**Issue by PandaWhoCodes** [pupil-labs/pyglui#71]
I have a visual studio 2017 and it keeps giving me this error
pyglui/cygl/utils.cpp(482): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory

Could someone plesae help out?

**Comment by willpatera** [comment]
Wheels are on the release page - https://github.com/pupil-labs/pyglui/releases/tag/v1.18
