### ISSUE TITLE
Support element-dependend cursor shape on hover

### ISSUE THREAD

**Issue by papr** [pupil-labs/pyglui#87]
It would be great if ui elements could tell the system to change the cursor shape on hovering it. E.g. `GLFW_IBEAM_CURSOR` for `Text_Input` or `GLFW_HRESIZE_CURSOR` for `Trim Marks`, etc

This would greatly improve the UX since users would notice areas of interaction that are currently hidden, e.g. draggable area of the Player seek handle.

We would need to extend `handle_input` to return a preferred cursor shape based on the input. The application managing the UI has to make the appropriate GLFW calls if the preferred cursor changes.
 
Further reading:
- http://www.glfw.org/docs/latest/input_guide.html#cursor_mode
- http://www.glfw.org/docs/latest/group__shapes.html

**Comment by mkassner** [comment]
Id rather work with the UI responding than the curser.

**Comment by papr** [comment]
Fixed with #88
