### ISSUE TITLE
Updated Version Format Crashes with Pupil Capture

### ISSUE THREAD

**Issue by mattem86** [pupil-labs/pyglui#98]
File "...\pupil\pupil_src\launchables\world.py", line 99, in world
    assert VersionFormat(pyglui_version) >= VersionFormat('1.15'), 'pyglui out of date, please upgrade to newest version'
AssertionError: pyglui out of date, please upgrade to newest version

Seems 1.7 is lower than 1.15 :)

**Comment by papr** [comment]
The current pyglui version is 1.18 Please upgrade to use the current Pupil master branch.

**Comment by mattem86** [comment]
ok, then it would be nice to deploy another pyglui binary, I downloaded the package on the release tab

**Comment by cboulay** [comment]
I just ran into this issue too.

**Comment by papr** [comment]
We will be uploading the newest pyglui wheel soon

**Comment by willpatera** [comment]
I will upload all new wheels on 2018-02-19 (Monday).

**Comment by willpatera** [comment]
@cboulay @mattem86 The pyglui `v1.18` wheel is here: https://github.com/pupil-labs/pyglui/releases/tag/v1.18
